# **Cross Validation** : *Comparing different models*

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

#### LogisticRegression score

In [4]:
lr=LogisticRegression(solver='sag', max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9592592592592593

#### RandomForestClassifier score

In [5]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9796296296296296

#### SVM score

In [6]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9907407407407407

## **K-Fold** 

In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
get_score(SVC(),X_train,X_test,y_train,y_test),get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

(0.9907407407407407, 0.9833333333333333)

## **Stratified** KFold

In [11]:
from sklearn.model_selection import StratifiedKFold 
skf= StratifiedKFold(n_splits=3)

In [12]:
scores_lr=[]
scores_svm=[]
scores_rf=[]

In [13]:
for train_index,test_index in skf.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append((get_score(LogisticRegression(solver='sag', max_iter=1000),X_train,X_test,y_train,y_test)))
    scores_svm.append((get_score(SVC(),X_train,X_test,y_train,y_test)))
    scores_rf.append((get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)))

In [14]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [15]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [16]:
scores_rf

[0.9382303839732888, 0.9632721202003339, 0.9232053422370617]

## **Cross Val Score** Evaluation

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
cross_val_score(LogisticRegression(solver='sag', max_iter=1000),digits.data,digits.target)

array([0.91944444, 0.86944444, 0.94428969, 0.93871866, 0.89972145])

In [19]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [20]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)  # to specify the number of folds in a `(Stratified)KFold

array([0.93155259, 0.95325543, 0.93656093])