# Predicting Salary of Employee w.r.t. given data 

### The hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates:-core

#### 1.) 2 yr experience, 9 test score, 6 interview score 
#### 2.) 12 yr experience, 10 test score, 10 interview score

In [1]:
from word2number import w2n
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
from sklearn import linear_model

In [2]:
df=pd.DataFrame(pd.read_csv('salary.csv'))

In [3]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

### Cleaning Data

In [4]:
ts_med=df.test_score.median()
ts_med

8.0

#### Filling missing data

In [5]:
df.test_score=df.test_score.fillna(ts_med)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

### Now converting word to number

In [6]:
df.experience = df.experience.fillna("zero")
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [7]:
lreg=linear_model.LinearRegression()
lreg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [8]:
lreg.intercept_

17737.26346433768

In [9]:
lreg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

#### 1.) 2 yr experience, 9 test score, 6 interview score 

In [10]:
lreg.predict([[2,9,6]])

D:\anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

#### 2.) 12 yr experience, 10 test score, 10 interview score

In [11]:
lreg.predict([[12,10,10]])

D:\anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])